wandb_version: 1

level1_model:
  desc: null
  value: MultinomialLogRegression
method:
  desc: null
  value: stacking
number of folds:
  desc: null
  value: 5
holdout fraction:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699757040.182862
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
