wandb_version: 1

num_trees:
  desc: null
  value: 7
bootstrap_fraction:
  desc: null
  value: 0.4
number of features:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699814884.681254
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
