wandb_version: 1

num_epoches:
  desc: null
  value: 700
learning_rate:
  desc: null
  value: 0.02
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698070549.804356
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.15.11
      8:
      - 1
      - 5
      13: linux-x86_64
