wandb_version: 1

layer_sizes:
  desc: null
  value:
  - 11
  - 5
  - 5
  - 6
batch_size:
  desc: null
  value: 100
num_epoches:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
activation_function:
  desc: null
  value: ReLU
optimization:
  desc: null
  value: mini-batch
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698066264.430027
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.15.11
      8:
      - 1
      - 5
      13: linux-x86_64
